import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Gift, Sparkles } from 'lucide-react';
import { birthdayConfig, routes } from './data/birthdayConfig';
import { CharacterCard, GiftBox, MemoryGallery } from './components/Cards';
import { MusicPlayer, ProgressBar } from './components/MusicPlayer';

const ButtonLink = ({ to, children = 'Continue →' }: { to: string; children?: React.ReactNode }) => (
  <Link to={to} className="inline-flex rounded-full bg-gradient-to-r from-[#ff91aa] to-[#f5d2ab] px-6 py-3 text-sm font-bold text-[#4a2531] shadow-lg transition hover:scale-105">{children}</Link>
);

const Heading = ({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle?: string }) => (
  <header className="mb-8 text-center"><p className="text-xs uppercase tracking-[.3em] text-[#9a707d]">{eyebrow}</p><h1 className="mt-2 font-script text-5xl text-[#432b34] sm:text-6xl">{title}</h1>{subtitle && <p className="mx-auto mt-3 max-w-xl text-[#65525a]">{subtitle}</p>}</header>
);

function Layout() {
  const location = useLocation();
  return <><ProgressBar routes={routes} /><div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_top,#ffe2d5,transparent_42%),linear-gradient(135deg,#fffaf5,#f8dce5)]" /><div className="pointer-events-none fixed inset-0 -z-10">{Array.from({ length: 16 }, (_, i) => <span key={i} className="particle" style={{ left: `${(i * 29) % 100}%`, top: `${(i * 37) % 100}%`, animationDelay: `${i * .4}s` }} />)}</div><MusicPlayer /><AnimatePresence mode="wait"><motion.main key={location.pathname} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -18 }} transition={{ duration: .3 }} className="mx-auto min-h-[calc(100vh-64px)] max-w-6xl px-4 py-10 sm:px-6"><Routes><Route path="/" element={<Navigate to="/welcome" replace />} /><Route path="/welcome" element={<Welcome />} /><Route path="/choose" element={<Choose />} /><Route path="/gift" element={<GiftPage />} /><Route path="/memories" element={<Memories />} /><Route path="/appreciation" element={<Appreciation />} /><Route path="/quiz" element={<Quiz />} /><Route path="/letter" element={<Letter />} /><Route path="*" element={<Navigate to="/welcome" replace />} /></Routes></motion.main></AnimatePresence></>;
}

function Welcome() { const navigate = useNavigate(); return <section className="flex min-h-[75vh] items-center justify-center"><div className="w-full max-w-xl rounded-[2rem] border border-white/50 bg-[#3d2435]/90 p-8 text-center text-white shadow-2xl backdrop-blur-xl"><Sparkles className="mx-auto mb-5 text-[#ffd9b2]" /><h1 className="font-script text-6xl">Hey... I made something for you.</h1><p className="mt-6 text-white/80">But you have to promise you'll explore everything 👀</p><button onClick={() => navigate('/choose')} className="mt-8 rounded-full bg-gradient-to-r from-[#ffd3be] to-[#ebd9ff] px-6 py-3 font-bold text-[#4b2c3d] transition hover:scale-105">Enter the birthday world →</button></div></section>; }

function Choose() { const [selected, setSelected] = useState<keyof typeof birthdayConfig.characterMessages | null>(null); return <><Heading eyebrow="A tiny introduction" title="Okay... let's start." subtitle="Pick one. Each one has something special to say." /><div className="grid gap-5 md:grid-cols-3">{Object.entries(birthdayConfig.characterMessages).map(([key, message]) => <CharacterCard key={key} character={key as keyof typeof birthdayConfig.characterMessages} message={message} selected={selected === key} onSelect={() => setSelected(key as keyof typeof birthdayConfig.characterMessages)} />)}</div>{selected && <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} className="mx-auto mt-8 max-w-lg rounded-3xl bg-white/75 p-6 text-center shadow-soft"><p className="text-[#59434d]">{birthdayConfig.characterMessages[selected]}</p><div className="mt-5"><ButtonLink to="/gift" /></div></motion.div>}</>; }

function GiftPage() { const [opened, setOpened] = useState(false); const [later, setLater] = useState(false); return <><Heading eyebrow="The secret gift" title="There's one more thing..." subtitle="Do you want to open your gift?" /><GiftBox opened={opened} />{!opened ? <div className="mt-6 flex flex-wrap justify-center gap-3"><button onClick={() => setOpened(true)} className="rounded-full bg-[#ff9cad] px-6 py-3 font-bold text-[#4c2432]">YES, OPEN IT 🎁</button><button onClick={() => setLater(true)} className="rounded-full border border-[#e4cfd2] bg-white/70 px-6 py-3 font-semibold">Maybe later...</button></div> : <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mx-auto mt-7 max-w-xl rounded-3xl bg-white/75 p-7 text-center shadow-soft"><Gift className="mx-auto text-[#e58a92]" /><h2 className="mt-3 font-script text-5xl text-[#482c35]">HAPPY BIRTHDAY, {birthdayConfig.bestFriendName.toUpperCase()} 🎂</h2><p className="mt-3">Today is your day.</p><div className="mt-5"><ButtonLink to="/memories" /></div></motion.div>}{later && <p className="mt-4 text-center">Nice try 😂</p>}</>; }

function Memories() { const [selected, setSelected] = useState<number | null>(null); return <><Heading eyebrow="A tiny archive" title="Little moments, big memories." subtitle="A few moments that deserve their own little corner of the internet." /><MemoryGallery selectedMemory={selected} onSelect={setSelected} />{selected !== null && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={() => setSelected(null)}><div className="max-w-xl rounded-3xl bg-white p-3" onClick={e => e.stopPropagation()}><img src={birthdayConfig.memoryCards[selected].image} alt={birthdayConfig.memoryCards[selected].caption} className="max-h-[70vh] w-full rounded-2xl object-contain" /><p className="p-3 text-center font-script text-3xl">{birthdayConfig.memoryCards[selected].caption}</p></div></div>}<div className="mt-8 text-center"><ButtonLink to="/appreciation" /></div></>; }

function Appreciation() { return <><Heading eyebrow="A heartfelt little list" title="Things I appreciate about you ❤️" /><div className="mx-auto max-w-3xl space-y-4">{birthdayConfig.appreciationCards.map((item, i) => <motion.div key={item.title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .08 }} className="flex items-center gap-4 rounded-3xl bg-white/75 p-5 shadow-soft"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#ffe2da] text-2xl">{item.icon}</span><div><h2 className="font-bold text-[#432d34]">{item.title}</h2><p className="text-sm text-[#66535a]">{item.description}</p></div></motion.div>)}</div><div className="mt-8 text-center"><ButtonLink to="/quiz" /></div></>; }

function Quiz() { const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [done, setDone] = useState(false); const q = birthdayConfig.quizQuestions[index]; const answer = (i: number) => { const next = score + (i === q.answerIndex ? 1 : 0); setScore(next); if (index === birthdayConfig.quizQuestions.length - 1) setDone(true); else setIndex(index + 1); }; if (done) return <div className="mx-auto max-w-xl rounded-3xl bg-white/75 p-8 text-center shadow-soft"><Heading eyebrow="Final score" title={`Friendship Memory Score: ${score}/${birthdayConfig.quizQuestions.length} 😂❤️`} /><p>Okay, you know me pretty well.</p><div className="mt-6"><ButtonLink to="/letter">Open the final letter 💌</ButtonLink></div></div>; return <><Heading eyebrow={`Question ${index + 1} of ${birthdayConfig.quizQuestions.length}`} title="How good is your memory? 👀" /><div className="mx-auto max-w-2xl rounded-3xl bg-white/75 p-6 shadow-soft"><h2 className="text-xl font-bold">{q.question}</h2><div className="mt-5 grid gap-3">{q.options.map((option, i) => <button key={option} onClick={() => answer(i)} className="rounded-2xl border border-[#efd9d7] bg-white/70 p-4 text-left transition hover:bg-[#fff0e8]">{option}</button>)}</div></div></>; }

function Letter() { const [open, setOpen] = useState(false); return <><Heading eyebrow="One final message" title="One final message..." /><div className="mx-auto max-w-2xl rounded-[2rem] bg-white/75 p-8 text-center shadow-soft">{!open ? <><motion.div animate={{ y: [0, -6, 0] }} transition={{ repeat: Infinity, duration: 2 }} className="mx-auto mb-6 text-8xl">💌</motion.div><button onClick={() => setOpen(true)} className="rounded-full bg-[#ff9caf] px-6 py-3 font-bold">Open the letter 💌</button></> : <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-left"><h2 className="font-script text-4xl">Happy Birthday, {birthdayConfig.bestFriendName} ❤️</h2><div className="mt-5 whitespace-pre-line leading-8 text-[#514047]">{birthdayConfig.finalLetter}</div><p className="mt-5 font-script text-3xl">— {birthdayConfig.yourName}</p></motion.div>}<div className="mt-8 border-t border-[#f0dcda] pt-5"><button onClick={() => window.location.assign('/welcome')} className="text-sm font-bold text-[#a64f68]">Replay the whole experience ↻</button><p className="mt-3 text-sm">Made with way too much effort 😂❤️</p></div></div></>; }

export default function App() { return <Layout />; }
